### PR TITLE
amt.ForEach respects internal cache

### LINKED ISSUE #19: ForEach does not properly iterate values prior to Flush
**Version**: github.com/filecoin-project/go-amt-ipld/v2 v2.0.1-0.20200424220931-6263827e49f2

**Problem:**
When attempting to iterate through the AMT prior to flushing, the behavior is unexpected. The following test:

1. Passes for the first case (`{ 0, 1, 2, 3, 4, 5, 6, 7}`).
2. Fails for `{8}`. The ForEach does not iterate over anything.
3. Fails for `{8, 9, 64}`. The ForEach iterates over 8 and 9, but not 64.
4. Fails for `{64, 8, 9,}`. The ForEach does not iterate at all

``` golang
func TestAMTForEachWorksBeforeFlush(t *testing.T) {
	rt := mock.NewBuilder(context.Background(), address.Undef).Build(t)
	store := adt.AsStore(rt)

	for _, vals := range [][]uint64{
		{0, 1, 2, 3, 4, 5, 6, 7},
		{8},
		{8, 9, 64},
		{64, 8, 9},
	} {
		amt := amt.NewAMT(store)
		set := make(map[uint64]struct{})
		for _, val := range vals {
			err := amt.Set(context.Background(), val, abi.ChainEpoch(0))
			require.NoError(t, err)

			set[val] = struct{}{}
		}

		amt.ForEach(context.Background(), func(u uint64, deferred *cbg.Deferred) error {
			delete(set, u)
			return nil
		})
		assert.Equal(t, make(map[uint64]struct{}), set)
	}
}
```

Adding an `amt.Flush(context.Background())` between the for loop and the `ForEach` allows all the tests to pass.

It may be acceptable to require flushing before iterating, but it should probably error immediately, since it's correct behavior for small numbers means mistakes will be easily missed.

### PR DESCRIPTION
**Pull request by acruikshank**
closes #19

### Motivation

The amt's `ForEach` ignores the cache. This means that changes that have been made since the last flush will not be iterated over by `ForEach` and that `ForEach` will make unnecessary reads from the store.

### Proposed Changes

1. When iterating over a node's values, check for value in cache first and use it if found.
2. Test that ForEach works before and after Flush.

### CODE REVIEW

File: amt.go [hunk 1]
```diff
@@ -285,21 +285,25 @@ func (n *Node) forEachAt(ctx context.Context, bs cbor.IpldStore, height int, sta
...
 	for i, v := range n.expLinks {
-		if v != cid.Undef {
-			offs := offset + (uint64(i) * subCount)
-			nextOffs := offs + subCount
-			if start >= nextOffs {
-				continue
-			}
-
-			var sub Node
+		var sub Node
```
Comment (Stebalien) [inline amt.go:288]: Do we really want to copy the node?

Comment (Stebalien) [reply amt.go:288]: Ok, I talked this over with @whyrusleeping and _not_ doing this could end up caching the entire tree in memory.

IMO, the _right_ way to do this would be to have some kind of "max cached nodes" limit, and flush when we hit that limit, but that's a larger refactor.
