### PR TITLE
avoid altering amt when empty

### LINKED ISSUE #18: ForEach mutates empty AMT
**Version:** github.com/filecoin-project/go-amt-ipld/v2 v2.0.1-0.20200424220931-6263827e49f2

**Problem:**
Flushing an empty AMT produces a different CID before and after a `ForEach` is run on it. The following test fails:
``` golang
func TestEmptyAMTRoot(t *testing.T) {
	ctx := context.Background()
	rt := mock.NewBuilder(context.Background(), address.Undef).Build(t)
	store := adt.AsStore(rt)
	root := amt.NewAMT(store)

	cid1, err := root.Flush(ctx)
	require.NoError(t, err)

	root.ForEach(ctx, func(_ uint64, _ *cbg.Deferred) error {
		return nil
	})

	cid2, err := root.Flush(ctx)
	require.NoError(t, err)

	assert.Equal(t, cid1, cid2)
}
```

The problem appears to be that the `expVals` slice is empty before the `ForEach` and is populated with 8 nil values after.

### PR DESCRIPTION
**Pull request by acruikshank**
closes #18

### Motivation

Actions like calling `ForEach` or adding and removing elements put an empty AMT into a state that causes it to be serialized differently even though it is still the empty array. This is because these actions cause `expVals` to be expanded in the node from a nil value to a slice with nil values. While `expVals` isn't itself serialized, The fact that it is non-nil causes the node's `Bmap` value to be initialized from a nil value to `[]byte{0}` in `Flush`, and that does serialize differently.

### Proposed Changes

1. Add a test to demonstrate the problem.
2. Initialize `Node.Bmap` lazily in `Flush`.

This is probably the simplest solution that fixes the problem. It leaves open a bigger question about whether empty nodes should be structurally different when serialized from nodes containing one or more elements. I find it a little surprising, but not really wrong.

### CODE REVIEW

File: amt_test.go [hunk 1]
```diff
@@ -3,6 +3,7 @@ package amt
 import (
 	"context"
 	"fmt"
+	"github.com/stretchr/testify/require"
```
Comment (Stebalien) [inline amt_test.go:6]: import order nit

**Comment by whyrusleeping** [comment]
I think I agree with @Stebalien , this value should always be set and never should be serialized as nil.

File: amt.go [hunk 2]
```diff
@@ -495,11 +495,14 @@ func (n *Node) Flush(ctx context.Context, bs cbor.IpldStore, depth int) error {
 		if len(n.expVals) == 0 {
 			return nil
 		}
-		n.Bmap = []byte{0}
+		n.Bmap = nil
```
Comment (whyrusleeping) [inline amt.go:498]: always defaulting to having the bitfield set would just mean moving this line (before this change) to above the `if`

**Comment by Stebalien** [comment]
Fix for byte arrays: https://github.com/whyrusleeping/cbor-gen/pull/29

**Comment by Stebalien** [comment]
Fix merged.

**Comment by Stebalien** [comment]
Fix pushed. Could you take a look at this @whyrusleeping and @acruikshank?
